# ------------------------------------------------------------------------------
# Install build tools and compile the code
FROM ubuntu:focal AS build
ADD . /src
WORKDIR /src
RUN apt-get update && \
	apt-get install -y build-essential \
	  libmicrohttpd-dev libhiredis-dev && \
	./compile_server.sh

# ------------------------------------------------------------------------------
# Pull base image
FROM ubuntu:focal
MAINTAINER Brett Kuskie <fullaxx@gmail.com>

# ------------------------------------------------------------------------------
# Set environment variables
ENV DEBIAN_FRONTEND noninteractive

# ------------------------------------------------------------------------------
# Install libraries and clean up
RUN apt-get update && \
	apt-get install -y --no-install-recommends \
	  libmicrohttpd12 libhiredis0.14 && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/* /var/tmp/* /tmp/*

# ------------------------------------------------------------------------------
# Install scripts and binaries
COPY app/app.webstore.sh /app/app.sh
COPY --from=build /src/webstore.exe /app/

# ------------------------------------------------------------------------------
# Add volumes
VOLUME /log

# ------------------------------------------------------------------------------
# Expose ports
EXPOSE 8080

# ------------------------------------------------------------------------------
# Define default command
CMD ["/app/app.sh"]
