# ------------------------------------------------------------------------------
# Install build tools and compile the code
FROM ubuntu:focal AS build
ADD src /src
WORKDIR /src
RUN apt-get update && \
	apt-get install -y build-essential \
	  libcurl4-gnutls-dev libgcrypt20-dev && \
	./compile_clients.sh

# ------------------------------------------------------------------------------
# Pull base image
FROM ubuntu:focal
MAINTAINER Brett Kuskie <fullaxx@gmail.com>

# ------------------------------------------------------------------------------
# Set environment variables
ENV DEBIAN_FRONTEND noninteractive

# ------------------------------------------------------------------------------
# Install libraries and clean up
RUN apt-get update && \
	apt-get install -y --no-install-recommends \
	  libcurl3-gnutls libgcrypt20 ca-certificates && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/* /var/tmp/* /tmp/*

# ------------------------------------------------------------------------------
# Install scripts and binaries
COPY app/app.wspost.sh /app/app.sh
COPY --from=build /src/ws_post.exe /app/

# ------------------------------------------------------------------------------
# Define default command
CMD ["/app/app.sh"]
